#!/usr/bin/env bash
# dogfood-digest-render.sh — render filtered dogfood JSONL (from dogfood-digest.sh)
# into a 3-section Markdown proposal report.
#
# Sections (fixed order, always present):
#   1. Threshold Calibration — qa_judge score distribution + axis_skip frequency.
#   2. Protocol Improvements — pain/ambiguous notes + recurring axis_skip reasons.
#   3. Promotion Candidates  — request/good notes + promotion_gate y-responses.
#
# Empty section → literal "> no signal in window" line per requirements SC-5.
#
# Each suggestion line includes a back-reference `\`path:line\`` (at least one).
#
# Recursion filter: drops skill_call events where skill references
# /crucible:dogfood-digest itself (dogfood skill also filters /crucible:dogfood).
#
# Input : JSONL on stdin (each line has _source_path, _line, ts, type, …).
# Args  :
#   --window <LABEL>     window label used in frontmatter + filename (required)
#   --scope  <SCOPE>     scope label stored in frontmatter (default: both)
#   --threshold-n <N>    minimum observation count for threshold suggestions
#                        (default: 3; lower values mean quieter logs still emit)
# Output: Markdown on stdout.
#
# Runtime: bash + jq. No Python / Node.

set -uo pipefail

window_label=""
scope_label="both"
threshold_n=3

while [[ $# -gt 0 ]]; do
    case "$1" in
        --window)
            window_label="${2:-}"
            shift 2 || { printf 'render: --window requires a value\n' >&2; exit 2; }
            ;;
        --scope)
            scope_label="${2:-}"
            shift 2 || { printf 'render: --scope requires a value\n' >&2; exit 2; }
            ;;
        --threshold-n)
            threshold_n="${2:-}"
            shift 2 || { printf 'render: --threshold-n requires a value\n' >&2; exit 2; }
            ;;
        *)
            printf 'render: unknown argument: %s\n' "$1" >&2
            exit 2
            ;;
    esac
done

if [[ -z "$window_label" ]]; then
    printf 'render: --window is required\n' >&2
    exit 2
fi

tmp_in="$(mktemp -t dogfood-digest-in.XXXXXX)"
trap 'rm -f "$tmp_in"' EXIT

# Read stdin, drop blanks, filter recursion events at ingestion.
jq -c 'select(if .type == "skill_call" then ((.skill // "") | test("crucible:dogfood-digest") | not) else true end)' > "$tmp_in" || true

total_events=$(wc -l < "$tmp_in" | tr -d ' ')

# ----- per-type aggregates ---------------------------------------------------

# qa_judge: score list + verdict histogram
qa_json="$(jq -sc '[.[] | select(.type=="qa_judge")]' "$tmp_in")"
qa_count=$(printf '%s' "$qa_json" | jq 'length')

# axis_skip: axis histogram (only "acknowledged" true)
skip_json="$(jq -sc '[.[] | select(.type=="axis_skip")]' "$tmp_in")"
skip_count=$(printf '%s' "$skip_json" | jq 'length')

# notes (pain + ambiguous) — Protocol
pain_json="$(jq -sc '[.[] | select(.type=="note" and (.category=="pain" or .category=="ambiguous"))]' "$tmp_in")"
pain_count=$(printf '%s' "$pain_json" | jq 'length')

# notes (request + good) — Promotion
promo_notes_json="$(jq -sc '[.[] | select(.type=="note" and (.category=="request" or .category=="good"))]' "$tmp_in")"
promo_notes_count=$(printf '%s' "$promo_notes_json" | jq 'length')

# promotion_gate y-responses — Promotion (response may be "y" or similar)
gate_json="$(jq -sc '[.[] | select(.type=="promotion_gate" and (.response // "") == "y")]' "$tmp_in")"
gate_count=$(printf '%s' "$gate_json" | jq 'length')

# source path counts for frontmatter
source_counts_json="$(jq -sc '[.[]._source_path] | group_by(.) | map({(.[0]): length}) | add // {}' "$tmp_in")"

# ----- frontmatter -----------------------------------------------------------

today="$(date -u +%Y-%m-%d)"

printf -- '---\n'
printf 'generated_at: "%s"\n' "$(date -u +%Y-%m-%dT%H:%M:%SZ)"
printf 'window: "%s"\n' "$window_label"
printf 'scope: "%s"\n' "$scope_label"
printf 'total_events: %s\n' "$total_events"
printf 'source_counts: %s\n' "$source_counts_json"
printf 'date: "%s"\n' "$today"
printf -- '---\n\n'

printf '# Dogfood Digest — %s (%s)\n\n' "$window_label" "$scope_label"
printf '> read-only proposal report generated by `/crucible:dogfood-digest`. this file is the only write.\n'
printf '> input: %s events from %s source(s).\n\n' "$total_events" "$(printf '%s' "$source_counts_json" | jq 'length')"

# ----- Section 1: Threshold Calibration --------------------------------------

printf '## Threshold Calibration\n\n'

if [[ "$qa_count" -lt "$threshold_n" && "$skip_count" -lt "$threshold_n" ]]; then
    printf '> no signal in window (qa_judge n=%s, axis_skip n=%s, threshold-n=%s)\n\n' \
        "$qa_count" "$skip_count" "$threshold_n"
else
    if [[ "$qa_count" -ge "$threshold_n" ]]; then
        # verdict histogram
        promote_n=$(printf '%s' "$qa_json" | jq '[.[] | select(.verdict=="promote")] | length')
        retry_n=$(printf '%s' "$qa_json" | jq '[.[] | select(.verdict=="retry")] | length')
        reject_n=$(printf '%s' "$qa_json" | jq '[.[] | select(.verdict=="reject")] | length')
        # percentiles via bash sort (scores are floats ≤ 3 digits)
        scores_sorted=$(printf '%s' "$qa_json" | jq -r '[.[].score] | sort | .[]' | paste -sd',' -)
        p50=$(printf '%s' "$scores_sorted" | tr ',' '\n' | awk 'BEGIN{c=0}{a[c++]=$1}END{ if(c==0){print "n/a"} else {print a[int((c-1)/2)]} }')
        p95=$(printf '%s' "$scores_sorted" | tr ',' '\n' | awk 'BEGIN{c=0}{a[c++]=$1}END{ if(c==0){print "n/a"} else { i=int((c-1)*0.95+0.5); if(i>=c)i=c-1; print a[i] } }')
        refs=$(printf '%s' "$qa_json" | jq -r '.[] | "\(._source_path):\(._line)"' | head -3 | awk '{printf "`%s` ", $0}')
        printf -- '- **qa_judge score distribution** — n=%s · p50=%s · p95=%s · verdicts: promote=%s · retry=%s · reject=%s — 근거(샘플 3건): %s\n' \
            "$qa_count" "$p50" "$p95" "$promote_n" "$retry_n" "$reject_n" "$refs"
        printf '  - 권고: 현행 임계값(promote ≥0.80 · reject ≤0.40) 재검토. p50 < 0.80 이면 해당 스킬의 평가 원칙 weight 재배분; retry 비율 > 40%% 이면 Ralph Loop 예산 (기본 3) 조정 검토.\n'
    else
        printf -- '- qa_judge 관측수 부족 (n=%s < %s) — 임계값 재조정 판단 보류.\n' "$qa_count" "$threshold_n"
    fi

    if [[ "$skip_count" -ge "$threshold_n" ]]; then
        axis_hist=$(printf '%s' "$skip_json" | jq -r '[.[].axis] | group_by(.) | map("axis=\(.[0]) ×\(length)") | join(" · ")')
        refs=$(printf '%s' "$skip_json" | jq -r '.[] | "\(._source_path):\(._line)"' | head -3 | awk '{printf "`%s` ", $0}')
        printf -- '- **axis_skip 빈도** — n=%s · 분포: %s — 근거(샘플 3건): %s\n' "$skip_count" "$axis_hist" "$refs"
        printf '  - 권고: 특정 축 skip 이 반복되면 ambiguity-gate 임계(현행 0.2) 재조정 또는 해당 축 HARD-GATE 완화 검토.\n'
    fi
    printf '\n'
fi

# ----- Section 2: Protocol Improvements --------------------------------------

printf '## Protocol Improvements\n\n'

if [[ "$pain_count" -eq 0 && "$skip_count" -eq 0 ]]; then
    printf '> no signal in window\n\n'
else
    if [[ "$pain_count" -gt 0 ]]; then
        # Group pain/ambiguous notes by first /crucible:* token in text; else bucket as "general".
        # Emit up to 5 grouped items.
        groups_json="$(printf '%s' "$pain_json" | jq -c '
            map({
                key: ((.text // "") | capture("(?<k>/crucible:[a-z0-9_-]+)"; "i").k // "general"),
                category: .category,
                text: (.text // ""),
                src: "\(._source_path):\(._line)"
            })
            | group_by(.key)
            | map({
                key: .[0].key,
                n: length,
                cats: [.[].category] | unique | join("+"),
                samples: [.[].text] | .[0:1],
                refs: [.[].src] | .[0:3]
            })
            | sort_by(-.n)
            | .[0:5]
        ')"
        if [[ "$(printf '%s' "$groups_json" | jq 'length')" -eq 0 ]]; then
            printf '> no signal in window\n\n'
        else
            printf '%s' "$groups_json" | jq -r '.[] | "- **\(.key)** (\(.cats), n=\(.n)) — \(.samples[0] // "")\n  - 근거: \(.refs | map("`\(.)`") | join(" "))"'
            printf '\n\n'
        fi
    fi
    if [[ "$skip_count" -ge 2 ]]; then
        skip_reasons=$(printf '%s' "$skip_json" | jq -c '
            [.[] | select(.reason != null) | {reason: .reason, src: "\(._source_path):\(._line)"}]
            | group_by(.reason)
            | map({reason: .[0].reason, n: length, refs: [.[].src] | .[0:3]})
            | map(select(.n >= 2))
            | .[0:3]
        ')
        if [[ "$(printf '%s' "$skip_reasons" | jq 'length')" -gt 0 ]]; then
            printf '%s' "$skip_reasons" | jq -r '.[] | "- **반복 skip reason**: \(.reason) (n=\(.n)) — 근거: \(.refs | map("`\(.)`") | join(" "))"'
            printf '\n\n'
        fi
    fi
fi

# ----- Section 3: Promotion Candidates ---------------------------------------

printf '## Promotion Candidates\n\n'

if [[ "$promo_notes_count" -eq 0 && "$gate_count" -eq 0 ]]; then
    printf '> no signal in window\n\n'
else
    if [[ "$promo_notes_count" -gt 0 ]]; then
        # Group request/good by first /crucible:* token.
        promo_groups="$(printf '%s' "$promo_notes_json" | jq -c '
            map({
                key: ((.text // "") | capture("(?<k>/crucible:[a-z0-9_-]+)"; "i").k // "general"),
                category: .category,
                text: (.text // ""),
                src: "\(._source_path):\(._line)"
            })
            | group_by(.key)
            | map({
                key: .[0].key,
                n: length,
                cats: [.[].category] | unique | join("+"),
                samples: [.[].text] | .[0:1],
                refs: [.[].src] | .[0:3]
            })
            | map(select(.n >= 1))
            | sort_by(-.n)
            | .[0:5]
        ')"
        if [[ "$(printf '%s' "$promo_groups" | jq 'length')" -gt 0 ]]; then
            printf '%s' "$promo_groups" | jq -r '.[] | "- **\(.key)** (\(.cats), n=\(.n)) — \(.samples[0] // "")\n  - 근거: \(.refs | map("`\(.)`") | join(" "))"'
            printf '\n\n'
        fi
    fi
    if [[ "$gate_count" -ge 2 ]]; then
        gate_refs=$(printf '%s' "$gate_json" | jq -r '.[] | "\(._source_path):\(._line)"' | head -3 | awk '{printf "`%s` ", $0}')
        printf -- '- **promotion_gate y-response ≥ 2** — n=%s — 근거: %s\n' "$gate_count" "$gate_refs"
        printf '  - 권고: 유저가 반복 승인한 패턴은 `/compound` 스킬의 기본 제안 후보로 앞당길 가치.\n\n'
    fi
fi

# ----- footer ---------------------------------------------------------------

printf -- '---\n\n'
printf '*이 리포트는 제안 전용이며 어떤 SKILL.md · memory · plugin.json 파일도 자동 수정하지 않는다. 실행 판단은 사용자 몫.*\n'
